---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.123.111"}]
  customize:
    cpus: 2
    memory: 3072

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.7
  - name: mwrock/Windows2012R2
    transport:
      name: winrm
      password: vagrant
      username: vagrant

suites:
  - name: default
    run_list:
      - recipe[aet::default]
    attributes:
      aet:
        activemq:
          jmx_ip: '192.168.123.111'
    includes:
      - centos-6.7
  - name: develop
    run_list:
      - recipe[aet::_develop]
      - recipe[aet::default]
    attributes:
      aet:
        activemq:
          jmx_ip: '192.168.123.111'
    includes:
      - centos-6.7
  - name: absurd
    run_list:
      - recipe[aet::prerequisites]
      - recipe[aet::firefox]
      - recipe[aet::karaf]
      - recipe[aet::deploy_configs]
      - recipe[aet::deploy_features]
      - recipe[aet::deploy_bundles]
      - recipe[aet::postdeploy_restart]
      - recipe[aet::browsermob]
    attributes:
    includes:
      - mwrock/Windows2012R2
