---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.123.111"}]
  customize:
    cpus: 2
    memory: 3072
  linked_clone: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.4

suites:
  - name: default
    run_list:
      - recipe[aet::default]
    attributes:
      aet:
        activemq:
          jmx_ip: '192.168.123.111'
  - name: seleniumgrid
    driver:
      network:
        - ["private_network", {ip: "192.168.123.112"}]
      customize:
        memory: 768
    run_list:
      - recipe[java::default]
      - recipe[aet::seleniumgrid_hub]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/seleniumgrid
# chef14 ok, systemd
  - name: apache
    run_list:
      - recipe[aet::apache]
    attributes:
# chef14 ok, sysvinit
  - name: mongo
    run_list:
      - recipe[aet::mongo]
    attributes:
# chef14 ok, sysvinit
  - name: activemq
    run_list:
      - recipe[aet::activemq]
    attributes:
# chef14 ok, systemd
  - name: browsermob
    run_list:
      - recipe[aet::browsermob]
    attributes:
# chef14 ok, sysvinit
  - name: tomcat
    run_list:
      - recipe[aet::tomcat]
    attributes:
# chef14 ok, systemd
  - name: karaf
    run_list:
      - recipe[aet::karaf]
    attributes:
