---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.123.111"}]
  customize:
    cpus: 2
    memory: 3072
  linked_clone: true

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.8

suites:
  - name: seleniumgrid
    driver:
      network:
        - ["private_network", {ip: "192.168.123.112"}]
      customize:
        memory: 768
    run_list:
      - recipe[java::default]
      - recipe[aet::seleniumgrid_hub]
    attributes:
      java:
        jdk_version: '8'
    verifier:
      inspec_tests:
        - test/seleniumgrid
  - name: apache2
    driver:
      network:
        - ["private_network", {ip: "192.168.123.113"}]
      customize:
        memory: 768
    run_list:
      - recipe[aet::apache]
    verifier:
      inspec_tests:
        - test/apache2
